### ISSUE TITLE
Previous/next on blog

### ISSUE THREAD

**Issue by mrspeaker** [blitz/x86.lol#6]
I really enjoyed going through all your blog posts this morning (even though most of it went right over my head!) - the only (very very minor) annoying thing was getting to the end of an article and then being "stuck". The only way to get to the next post was to go home and remember which was next: some previous/next buttons would be good.

Also, after reading the articles I started going off on a hunt to find "less in-depth" articles to understand some of the concepts you were discussing. I'm not sure you have any interest in that, but doing some "x86 for newbies/intermediate" articles could be good too!

Thanks again

**Comment by blitz** [comment]
@mrspeaker Thank you for the warm words! Regarding the "next button": Good suggestion. I'll check out whether I can convice the site generator to insert that. 

As for newbie articles: Feel free to propose a topic! :)
